config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins
  resources :articles do 
    resources :comments
  end
  root to: 'welcome#index'
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  	before_action :configure_permitted_parameters, if: :devise_controller?
	protected

	def configure_permitted_parameters
  		devise_parameter_sanitizer.for(:sign_up) << :name
  		devise_parameter_sanitizer.for(:account_update) << :name
	end
  	protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	
  def index
    @articles = Article.all
  end
 
  def show
    @article = Article.find(params[:id])
  end
 
  def new
    @article = Article.new
  end
 
  def edit
    @article = Article.find(params[:id])
  end
 
  def create
    @article = Article.new(article_params)
 
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end
 
  def update
    @article = Article.find(params[:id])
 
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end
 
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
 
    redirect_to articles_path
  end
 
  private
    def article_params
      params.require(:article).permit(:title, :text)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  http_basic_authenticate_with name: "aditya", password: "pass123", only: :destroy
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end
 
  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end
 
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<html>
<head>
  <meta charset="utf-8">
  <div class="fr-view">
      <p>
        <%= f.label :title %><br>
        <%= f.text_field :title %>
      </p>
      <p>
        <%= f.text_area :text %>
      </p>
      <p>
        <%= f.submit %>
      </p>
  </div>

  <!-- Initialize the editor. -->
  <script>
      $(function() {
          $('#article_text').froalaEditor()
      });
  </script>
</body>
</html>

<% end %>

app/views/articles/edit.html.erb
<h1>Edit the current blog post --></h1>
<div class="fr-view">
  <%= form_for :article, url: article_path(@article), method: :patch do |f| %>
  <%= render 'form' %>

  <%= link_to 'Back', articles_path %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <% end %>
</div>

app/views/articles/index.html.erb
<h1><u>BlogAway! -- Your recent posts: </u></h1>
<div class="fr-view">
  <%= link_to 'Create New Blog Post', new_article_path %><br><br>
  <table>
    <tr>
      <th>Title</th>
      <th>Post</th>
      <th colspan="4"></th>
    </tr>
 
    <% @articles.each do |article| %>
      <tr>
        <td><%= raw article.title %></td>
        <td><%= raw article.text %></td>
        <td><%= link_to 'Show', article_path(article) %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article_path(article),
                method: :delete,
                data: { confirm: 'Are you sure you want to delete this post?' } %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/articles/new.html.erb
<h1>Create a new blog post --> </h1>
<%= form_for :article, url: articles_path do |f| %>
	<%= render 'form' %>
	<%= link_to 'Back', articles_path %>
<%end%>

app/views/articles/show.html.erb
<h1>Current post --></h1>
<div class="fr-view">
	<p>
	  <strong>Title of the post --></strong>
	  <%= raw @article.title %>
	</p>
	<p>
	  <strong>Post content --></strong>
	  <%= raw @article.text %>
	</p>
	 
	<h2>Comments: </h2>
	<%= render @article.comments %>
	 
	<h2>Add a comment:</h2>
	<%= render 'comments/form' %>
</div>
<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/comments/_comment.html.erb
<p>
  <strong><%= raw comment.commenter %></strong> : <%= raw comment.body %>
  <%= link_to 'Destroy Comment', [comment.article, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
<meta charset="utf-8">
<div class="fr-view">
  <p>
    <%= f.label "Comment as: " %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
  <script>
      $(function() {
          $('#comment_body').froalaEditor()
      });
  </script>
<% end %>
</div>

app/views/comments/_show.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
		<li><%= link_to 'Home', root_path %></li>
        <% if user_signed_in? %>
              <%= current_user.name %>
              <li><%= link_to 'Profile', edit_user_registration_path %></li>
              <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
        <% end %>
<%= yield %>

</body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.erb
<h1>Welcome to BlogAway -- Your beginner friendly blog maker</h1>
<div class="container">
	<% if user_signed_in? %>
            <li><%= link_to 'Blog Posts', :controller =>'articles' %></li>
			<li><%= link_to 'New Blog Post', :controller =>'articles' , :action =>'new' %></li>
    <% else %>
          	<strong>New User ? <%= link_to 'Sign Up', new_user_registration_path %></strong><br><br>
          	<strong>Returning Back ? <%= link_to 'Log In', new_user_session_path %></strong><br>
    <% end %>
</div>